# https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=

# unstable features are only available in nightly channel.
# wrap_comments = true
# comment_width = 120

max_width = 100
newline_style = "Unix"