name: Release
# on:
#   push:
#     tags:
#       - 'v*'

jobs:

  create-release:
    name: create release job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: generate changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with: 
          config: cliff.toml
          args: -vv --latest
        env:
          OUTPUT: CHANGELOG.md
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    needs: create-release
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and build
        id: compile
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          EXTRA_FILES: "README.md LICENSE"
          TOOLCHAIN_VERSION: stable
          UPLOAD_MODE: none
      - name: echo rust-build out
        run: |
          echo 'BUILT_ARCHIVE = ' + ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          echo 'BUILT_CHECKSUM = ' + ${{ steps.compile.outputs.BUILT_CHECKSUM }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload checksum to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.compile.outputs.BUILT_CHECKSUM }}
          tag: ${{ github.ref }}
          overwrite: true